#!/bin/sh /etc/rc.common
 
 
USE_PROCD=1
START=99
STOP=01
 
CONFIGURATION=modbus


start_service() {

    config_load "${CONFIGURATION}"

    procd_open_instance
    procd_set_param command /usr/bin/mgc
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/config/modbus
    procd_set_param pidfile /var/run/modbus.pid
    procd_close_instance
}

stop_service() {
    echo "modbus read stopped"
}